# Generated by Django 3.0.5 on 2020-05-04 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='passport',
            field=models.ImageField(blank=True, upload_to='students/passports/'),
        ),
    ]
