# Generated by Django 3.1 on 2021-01-26 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0002_auto_20201124_0608'),
    ]

    operations = [
    ]
