# Generated by Django 3.0.5 on 2020-04-29 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('finance', '0001_initial'),
        ('corecode', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Student'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corecode.AcademicTerm'),
        ),
    ]
