# Generated by Django 4.1.5 on 2023-02-20 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='serial',
            field=models.CharField(max_length=200, verbose_name='Серия'),
        ),
    ]
