# Generated by Django 4.1.5 on 2023-02-22 12:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0002_alter_doc_serial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doc',
            name='citizenship',
        ),
        migrations.AddField(
            model_name='doc',
            name='date_of_preparing',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Начать оформить до'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='date_of_expiry',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Действует до'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='date_of_issue',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата выдачи'),
        ),
    ]
