# Generated by Django 3.0.5 on 2020-05-04 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0002_auto_20200429_1519'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicterm',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='studentclass',
            options={'ordering': ['name'], 'verbose_name': 'Class', 'verbose_name_plural': 'Classes'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['name']},
        ),
    ]
