# Generated by Django 4.1.5 on 2023-01-30 15:33

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20201124_0614'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='position',
            field=models.CharField(default='кто-то', max_length=200, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='student',
            name='current_status',
            field=models.CharField(choices=[('active', 'Работает'), ('inactive', 'Уволенный')], default='active', max_length=10, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_of_admission',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата приема'),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='student',
            name='firstname',
            field=models.CharField(max_length=200, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('male', 'Муж'), ('female', 'Жен')], default='male', max_length=10, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='student',
            name='other_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent_mobile_number',
            field=models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator(message="Entered mobile number isn't in a right format!", regex='^[0-9]{10,15}$')], verbose_name='Тел номер'),
        ),
        migrations.AlterField(
            model_name='student',
            name='passport',
            field=models.ImageField(blank=True, upload_to='students/passports/', verbose_name='Паспорт'),
        ),
        migrations.AlterField(
            model_name='student',
            name='registration_number',
            field=models.CharField(max_length=200, unique=True, verbose_name='Табельный номер'),
        ),
        migrations.AlterField(
            model_name='student',
            name='surname',
            field=models.CharField(max_length=200, verbose_name='Фамилия'),
        ),
    ]
