# Generated by Django 4.1.5 on 2023-02-04 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_alter_employee_snils_number'),
        ('corecode', '0006_citizenship'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DocumentCategory',
            new_name='PermitDocCategory',
        ),
    ]
