# Generated by Django 4.1.5 on 2023-02-08 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0008_documenttype_document'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
