# Generated by Django 4.1.5 on 2024-02-28 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0009_delete_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gen_DT_Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CountryCode', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100, verbose_name='CountryEN')),
                ('CountryRU', models.CharField(max_length=100)),
                ('CountryTR', models.CharField(max_length=100)),
                ('AlphaCode2', models.CharField(default='000', max_length=10, verbose_name='AlphaCode(2)')),
                ('AlphaCode3', models.CharField(max_length=10, verbose_name='AlphaCode(3)')),
                ('CountriesForRF', models.BooleanField(default=False)),
                ('LocalEEC', models.BooleanField(default=False, verbose_name='Local/ EEC')),
                ('RvpVnj', models.BooleanField(default=False, verbose_name='RVP/ VNJ')),
                ('Visa', models.BooleanField(default=False)),
                ('VKS', models.BooleanField(default=False)),
                ('Patent', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='citizenship',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
