# Generated by Django 4.1.5 on 2024-02-28 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0010_gen_dt_country_alter_citizenship_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gen_DT_DocumentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DocumentTypeEN', models.CharField(max_length=200)),
                ('DocumentTypeRU', models.CharField(max_length=200)),
                ('DocumentTypeTR', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['DocumentTypeEN'],
            },
        ),
    ]
