# Generated by Django 4.1.5 on 2024-02-28 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0011_gen_dt_documenttype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gen_DT_Country',
        ),
    ]
