# Generated by Django 4.1.5 on 2024-02-28 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0012_delete_gen_dt_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gen_DT_Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CountryCode', models.CharField(max_length=50, unique=True)),
                ('CountryEN', models.CharField(max_length=100)),
                ('CountryRU', models.CharField(max_length=100)),
                ('CountryTR', models.CharField(max_length=100)),
                ('AlphaCode2', models.CharField(max_length=10, verbose_name='AlphaCode(2)')),
                ('AlphaCode3', models.CharField(max_length=10, verbose_name='AlphaCode(3)')),
                ('CountriesForRF', models.BooleanField(default=False)),
                ('LocalEEC', models.BooleanField(default=False, verbose_name='Local/ EEC')),
                ('RvpVnj', models.BooleanField(default=False, verbose_name='RVP/ VNJ')),
                ('Visa', models.BooleanField(default=False)),
                ('VKS', models.BooleanField(default=False)),
                ('Patent', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['CountryEN'],
            },
        ),
    ]
