# Generated by Django 4.1.5 on 2024-02-28 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0013_gen_dt_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gen_DT_Discipline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DisciplineEN', models.CharField(max_length=200)),
                ('DisciplineRU', models.CharField(max_length=200)),
                ('DisciplineTR', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['DisciplineEN'],
            },
        ),
    ]
