# Generated by Django 4.1.5 on 2024-02-28 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0014_gen_dt_discipline'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gen_DT_LevelEmp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LevelEmpEN', models.CharField(max_length=200)),
                ('LevelEmpRU', models.CharField(max_length=200)),
                ('LevelEmpTR', models.CharField(max_length=200)),
                ('OfficeEmp', models.BooleanField(default=False)),
                ('ProjectEmp', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['LevelEmpEN'],
            },
        ),
    ]
