# Generated by Django 4.1.5 on 2024-02-28 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0015_gen_dt_levelemp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gen_DT_EmpClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmpClassEN', models.CharField(max_length=200)),
                ('EmpClassRU', models.CharField(max_length=200)),
                ('EmpClassTR', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['EmpClassEN'],
            },
        ),
    ]
