# Generated by Django 4.1.5 on 2024-02-28 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0016_gen_dt_empclass'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gen_DT_JobTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JobTitleEN', models.CharField(max_length=200)),
                ('JobTitleRU', models.CharField(max_length=200)),
                ('JobTitleTR', models.CharField(max_length=200)),
                ('EmpClass', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corecode.gen_dt_empclass', verbose_name='Employee Class')),
                ('LevelEmp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corecode.gen_dt_levelemp', verbose_name='Employee Level')),
            ],
            options={
                'ordering': ['JobTitleEN'],
            },
        ),
    ]
