# Generated by Django 4.1.5 on 2024-02-28 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0017_gen_dt_jobtitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gen_DT_Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CurrencyNumber', models.IntegerField(max_length=50, unique=True)),
                ('CurrencyID_1C', models.CharField(max_length=100)),
                ('CurrencyCode', models.CharField(max_length=100)),
                ('CountryAlphaCode2', models.CharField(max_length=10, verbose_name='AlphaCode(2)')),
                ('CountryAlphaCode3', models.CharField(max_length=10, verbose_name='AlphaCode(3)')),
                ('CurrencyEN', models.CharField(max_length=200)),
                ('CurrencyRU', models.CharField(max_length=200)),
                ('CurrencyTR', models.CharField(max_length=200)),
                ('ActiveCurr', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['CurrencyNumber'],
            },
        ),
    ]
