# Generated by Django 4.1.5 on 2024-02-28 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0018_gen_dt_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gen_dt_currency',
            name='CurrencyNumber',
            field=models.IntegerField(unique=True),
        ),
    ]
