# Generated by Django 4.1.5 on 2024-02-28 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0021_gen_dt_counterparty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gen_DT_SubjectOfRF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SubjectOfRF_EN', models.CharField(max_length=200)),
                ('SubjectOfRF_RU', models.CharField(max_length=200)),
                ('SubjectOfRF_TR', models.CharField(max_length=200)),
                ('SubjRF_Abbreviation', models.CharField(max_length=200)),
                ('FederalDistrictEN', models.CharField(max_length=200)),
                ('FederalDistrictRU', models.CharField(max_length=200)),
                ('FederalDistrictTR', models.CharField(max_length=200)),
                ('OKATO_CODE', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['SubjectOfRF_EN'],
            },
        ),
    ]
