# Generated by Django 4.1.5 on 2024-02-28 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0023_gen_dt_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gen_DT_CounterPartyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CounterPartyTypeEN', models.CharField(max_length=200)),
                ('CounterPartyTypeRU', models.CharField(max_length=200)),
                ('CounterPartyTypeTR', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['CounterPartyTypeEN'],
            },
        ),
    ]
