# Generated by Django 4.1.5 on 2024-02-28 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0024_gen_dt_counterpartytype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gen_DT_ContractType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ContractTypeEN', models.CharField(max_length=200)),
                ('ContractTypeRU', models.CharField(max_length=200)),
                ('ContractTypeTR', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['ContractTypeEN'],
            },
        ),
        migrations.CreateModel(
            name='Gen_DT_VAT_Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VAT_Rate', models.IntegerField()),
            ],
            options={
                'ordering': ['VAT_Rate'],
            },
        ),
        migrations.AddField(
            model_name='gen_dt_counterparty',
            name='Supplier',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Gen_DT_Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ContractID_1C', models.CharField(max_length=100)),
                ('ContractsNo', models.CharField(max_length=200)),
                ('ContractDate', models.DateField()),
                ('ContractsSubject', models.CharField(max_length=200)),
                ('ContractAmountVatWo', models.FloatField()),
                ('ContractStartDate', models.DateField()),
                ('ContractEndDate', models.DateField()),
                ('ContractType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corecode.gen_dt_contracttype', verbose_name='Contract Type')),
                ('CounterParty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corecode.gen_dt_counterparty', verbose_name='Counter Party')),
                ('CounterPartyType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corecode.gen_dt_counterpartytype', verbose_name='Counter Party Type')),
                ('Currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corecode.gen_dt_currency', verbose_name='Currency')),
                ('Project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corecode.gen_dt_project', verbose_name='Project')),
                ('VAT_Rate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corecode.gen_dt_vat_rate', verbose_name='VAT Rate')),
            ],
            options={
                'ordering': ['ContractsSubject'],
            },
        ),
    ]
