# Generated by Django 4.1.5 on 2024-02-28 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0025_gen_dt_contracttype_gen_dt_vat_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gen_DT_UoM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UoM_Code_1C', models.CharField(max_length=200)),
                ('UoM_Short_EN', models.CharField(max_length=200)),
                ('UoM_Short_RU', models.CharField(max_length=200)),
                ('UoM_Short_TR', models.CharField(max_length=200)),
                ('UoM_EN', models.CharField(max_length=200)),
                ('UoM_RU', models.CharField(max_length=200)),
                ('UoM_TR', models.CharField(max_length=200)),
                ('UoM_Active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['UoM_Short_EN'],
            },
        ),
    ]
