# Generated by Django 4.1.5 on 2024-02-28 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0026_gen_dt_uom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gen_DT_BudgetData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BudgetVersion', models.IntegerField()),
                ('BudgetCode', models.CharField(max_length=100)),
                ('PrimaveraCode', models.CharField(max_length=100)),
                ('StartOfWorkDate', models.DateField()),
                ('EndOfWorkDate', models.DateField()),
                ('EmpQty', models.IntegerField()),
                ('EmpNetSalary', models.FloatField()),
                ('Currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corecode.gen_dt_currency', verbose_name='Currency')),
                ('Discipline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corecode.gen_dt_discipline', verbose_name='Discipline')),
                ('JotTitle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corecode.gen_dt_jobtitle', verbose_name='Job Title')),
                ('LegDocumentType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corecode.gen_dt_documenttype', verbose_name='Document Type')),
                ('UoM', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corecode.gen_dt_uom', verbose_name='UoM')),
            ],
            options={
                'ordering': ['BudgetVersion'],
            },
        ),
    ]
