# Generated by Django 4.1.5 on 2024-02-28 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0027_gen_dt_budgetdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gen_DT_BudgetDataHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BudgetDate', models.DateField()),
                ('BudgetID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corecode.gen_dt_budgetdata', verbose_name='Budget ID')),
                ('ProjectID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corecode.gen_dt_project', verbose_name='Project ID')),
            ],
            options={
                'ordering': ['BudgetDate'],
            },
        ),
    ]
