# Generated by Django 4.1.5 on 2024-02-28 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0029_gen_dt_expensefrequency_gen_dt_expensetype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gen_DT_LegalExpences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ExpensePrice', models.FloatField()),
                ('LegalExpenseActive', models.BooleanField(default=True)),
                ('EffectiveDate', models.DateField()),
                ('Currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corecode.gen_dt_currency', verbose_name='Currency')),
                ('ExpeneseCountry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corecode.gen_dt_country', verbose_name='Expenese Country')),
                ('ExpenseType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corecode.gen_dt_expensetype', verbose_name='Expense Type')),
                ('LegDocumentType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corecode.gen_dt_documenttype', verbose_name='Document Type')),
                ('ProjectID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corecode.gen_dt_project', verbose_name='Project ID')),
            ],
            options={
                'ordering': ['ProjectID'],
            },
        ),
    ]
