# Generated by Django 4.1.5 on 2024-02-28 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0030_gen_dt_legalexpences'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gen_DT_EmpLegalStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmpLegalStatusEN', models.CharField(max_length=200)),
                ('EmpLegalStatusRU', models.CharField(max_length=200)),
                ('EmpLegalStatusTR', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['EmpLegalStatusEN'],
            },
        ),
    ]
