# Generated by Django 4.1.5 on 2024-02-28 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0031_gen_dt_emplegalstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gen_DT_EmpLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmpLevelEN', models.CharField(max_length=200)),
                ('EmpLevelRU', models.CharField(max_length=200)),
                ('EmpLevelTR', models.CharField(max_length=200)),
                ('OfficeEmp', models.BooleanField(default=False)),
                ('ProjectEmp', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['EmpLevelEN'],
            },
        ),
        migrations.RemoveField(
            model_name='gen_dt_jobtitle',
            name='LevelEmp',
        ),
        migrations.DeleteModel(
            name='Gen_DT_LevelEmp',
        ),
        migrations.AddField(
            model_name='gen_dt_jobtitle',
            name='EmpLevel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corecode.gen_dt_emplevel', verbose_name='Employee Level'),
        ),
    ]
