# Generated by Django 4.1.5 on 2024-02-28 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0032_gen_dt_emplevel_remove_gen_dt_jobtitle_levelemp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gen_DT_EmpTaxType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmpTaxTypeEN', models.CharField(max_length=200)),
                ('EmpTaxTypeRU', models.CharField(max_length=200)),
                ('EmpTaxTypeTR', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['EmpTaxTypeEN'],
            },
        ),
    ]
