# Generated by Django 4.1.5 on 2024-02-28 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0034_gen_dt_emptaxpayer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gen_DT_OurCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OurCompanyID_1C', models.CharField(max_length=100)),
                ('OurCompanyEN', models.CharField(max_length=200)),
                ('OurCompanyRU', models.CharField(max_length=200)),
                ('OurCompanyTR', models.CharField(max_length=200)),
                ('OurCompanyINN', models.CharField(max_length=200)),
                ('OurCompanyKPP', models.CharField(max_length=200)),
                ('ShortCode', models.CharField(max_length=100)),
                ('TaxPayer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corecode.gen_dt_emptaxpayer', verbose_name='VAT Rate')),
            ],
            options={
                'ordering': ['OurCompanyEN'],
            },
        ),
        migrations.AddField(
            model_name='gen_dt_contract',
            name='OurCompany',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corecode.gen_dt_ourcompany', verbose_name='VAT Rate'),
        ),
    ]
