# Generated by Django 4.1.5 on 2024-02-29 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0035_gen_dt_ourcompany_gen_dt_contract_ourcompany'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gen_dt_contract',
            name='OurCompany',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corecode.gen_dt_ourcompany', verbose_name='Our Company'),
        ),
        migrations.AlterField(
            model_name='gen_dt_ourcompany',
            name='TaxPayer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corecode.gen_dt_emptaxpayer', verbose_name='Tax Payer'),
        ),
        migrations.CreateModel(
            name='Gen_DT_EmpTaxCalc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmpTaxRateEN', models.CharField(max_length=200)),
                ('EmpTaxRateRU', models.CharField(max_length=200)),
                ('EmpTaxRateTR', models.CharField(max_length=200)),
                ('TaxCodeSSF', models.IntegerField()),
                ('TaxCodePIT_Until182day', models.IntegerField()),
                ('TaxCodePIT_After182day', models.IntegerField()),
                ('LegDocumentType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corecode.gen_dt_documenttype', verbose_name='Document Type')),
            ],
            options={
                'ordering': ['EmpTaxRateEN'],
            },
        ),
    ]
