# Generated by Django 4.1.5 on 2023-02-01 13:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('corecode', '0004_auto_20201124_0614'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeBulkUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_uploaded', models.DateTimeField(auto_now=True)),
                ('csv_file', models.FileField(upload_to='employees/bulkupload/')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_status', models.CharField(choices=[('active', 'Работает'), ('inactive', 'Уволенный')], default='active', max_length=10, verbose_name='Статус')),
                ('registration_number', models.CharField(max_length=200, unique=True, verbose_name='Табельный номер')),
                ('surname', models.CharField(max_length=200, verbose_name='Фамилия')),
                ('firstname', models.CharField(max_length=200, verbose_name='Имя')),
                ('other_name', models.CharField(blank=True, max_length=200, verbose_name='Отчество')),
                ('gender', models.CharField(choices=[('male', 'Муж'), ('female', 'Жен')], default='male', max_length=10, verbose_name='Пол')),
                ('date_of_birth', models.DateField(default=django.utils.timezone.now, verbose_name='Дата рождения')),
                ('position', models.CharField(max_length=200, verbose_name='Должность')),
                ('date_of_admission', models.DateField(default=django.utils.timezone.now, verbose_name='Дата приема')),
                ('parent_mobile_number', models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator(message="Entered mobile number isn't in a right format!", regex='^[0-9]{10,15}$')], verbose_name='Тел номер')),
                ('address', models.TextField(blank=True)),
                ('others', models.TextField(blank=True)),
                ('passport', models.ImageField(blank=True, upload_to='Eeployee/passports/', verbose_name='Паспорт')),
                ('current_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corecode.studentclass')),
            ],
            options={
                'ordering': ['surname', 'firstname', 'other_name'],
            },
        ),
    ]
