# Generated by Django 4.1.5 on 2023-02-03 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='passport',
            field=models.ImageField(blank=True, upload_to='employees/passports/', verbose_name='Паспорт'),
        ),
    ]
