# Generated by Django 4.1.5 on 2023-02-04 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0006_citizenship'),
        ('employees', '0003_rename_date_of_admission_employee_date_of_employment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='address',
            field=models.TextField(blank=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='current_doc_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corecode.documentcategory', verbose_name='Категория документа'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='others',
            field=models.TextField(blank=True, verbose_name='Другие'),
        ),
    ]
