# Generated by Django 4.1.5 on 2023-02-04 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0006_citizenship'),
        ('employees', '0004_alter_employee_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='citizenship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corecode.citizenship', verbose_name='Гражданство'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='address',
            field=models.TextField(blank=True, verbose_name='Адрес в РФ'),
        ),
    ]
