# Generated by Django 4.1.5 on 2023-02-04 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_employee_citizenship_alter_employee_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='snils_number',
            field=models.CharField(blank=True, max_length=200, verbose_name='ИНН'),
        ),
        migrations.AddField(
            model_name='employee',
            name='tin_number',
            field=models.CharField(blank=True, max_length=200, verbose_name='ИНН'),
        ),
    ]
