# Generated by Django 4.1.5 on 2023-02-22 12:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_alter_employee_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='date_of_dismissal',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата увольнение'),
        ),
    ]
