# Generated by Django 4.1.5 on 2023-02-22 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_employee_date_of_dismissal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_of_dismissal',
            field=models.DateField(verbose_name='Дата увольнение'),
        ),
    ]
